module Models
  class MarketProjection
    COMPETITION = 'COMPETITION'.freeze
    EVENT = 'EVENT'.freeze
    EVENT_TYPE = 'EVENT_TYPE'.freeze
    MARKET_START_TIME = 'MARKET_START_TIME'.freeze
    MARKET_DESCRIPTION = 'MARKET_DESCRIPTION'.freeze
    RUNNER_DESCRIPTION = 'RUNNER_DESCRIPTION'.freeze
    RUNNER_METADATA = 'RUNNER_METADATA'.freeze
  end
end