require_relative 'betscrape/api/client'
require_relative 'betscrape/api/login_client'
require_relative 'betscrape/api/logger'

require_relative 'betscrape/models/competition'
require_relative 'betscrape/models/country'
require_relative 'betscrape/models/event_type'
require_relative 'betscrape/models/event'
require_relative 'betscrape/models/market_filter'
require_relative 'betscrape/models/market'
require_relative 'betscrape/models/market/market_description'
require_relative 'betscrape/models/market/market_projection'
require_relative 'betscrape/models/market/market_sort'
require_relative 'betscrape/models/market_book'
require_relative 'betscrape/models/market_book/order_projection'
require_relative 'betscrape/models/market_book/price_projection'
require_relative 'betscrape/models/market_book/match_projection'
require_relative 'betscrape/models/market_runner'
require_relative 'betscrape/models/market_runner/best_offer'
require_relative 'betscrape/models/market_runner/best_offers'

require_relative 'betscrape/scrape/competition_scraper'
